version: 2.1
orbs:
  docker: circleci/docker@0.2.0
environment:
  GRADLE_OPTS: -Xmx2048m -Dorg.gradle.daemon=false
commands:
  build:
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Gradle build
          command: |
            ./gradlew --parallel docker jacocoRootReport sonarqube \
            -Dsonar.projectKey=clouditor_clouditor \
            -Dsonar.organization=clouditor \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
  push:
    parameters:
      tag:
        type: string
        default: "latest"
    steps:
      - docker/check
      - docker/push:
          image: clouditor/engine
          tag: << parameters.tag >>
      - docker/push:
          image: clouditor/ui
          tag: << parameters.tag >>
      - docker/push:
          image: clouditor/clouditor
          tag: << parameters.tag >>
jobs:
  build_only:
    docker:
      - image: circleci/openjdk:11
    environment:
      GRADLE_OPTS: -Xmx2048m -Dorg.gradle.daemon=false
    steps:
      - build
  build_and_push:
    docker:
      - image: circleci/openjdk:11
    steps:
      - build
      - push
  build_and_push_release:
    docker:
      - image: circleci/openjdk:11
    steps:
      - build
      - run:
          command: |
            docker tag clouditor/engine clouditor/engine:$CIRCLE_TAG
            docker tag clouditor/ui clouditor/ui:$CIRCLE_TAG
            docker tag clouditor/clouditor clouditor/clouditor:$CIRCLE_TAG
      - push:
          tag: $CIRCLE_TAG
  build_and_push_eusec:
    docker:
      - image: circleci/openjdk:11
    steps:
      - build
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
      - run:
          name: Tag EU-SEC Pilot Build
          command: |
            docker tag clouditor/clouditor clouditor/clouditor:eu-sec
      - docker/check
      - docker/push:
          image: clouditor/clouditor
          tag: eu-sec
workflows:
  build:
    jobs:
      - build_only:
          context: org-global
          filters:
            branches:
              ignore:
                - master
                - eu-sec
      - build_and_push:
          context: org-global
          filters:
            branches:
              only: master
      - build_and_push_release:
          context: org-global
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build_and_push_eusec:
          context: org-global
          filters:
            branches:
              only:
                - eu-sec
